# Generated by Django 5.0.3 on 2024-03-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anonymous Author', max_length=100)),
                ('title', models.CharField(default='Untitled Research', max_length=200)),
                ('abstract', models.TextField(default='No abstract available.')),
            ],
        ),
    ]
