# Generated by Django 5.0.3 on 2024-03-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResearchPaper',
            new_name='Authors',
        ),
    ]
