# Generated by Django 5.0.3 on 2024-03-08 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_rename_researchpaper_authors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Thesis',
        ),
    ]
