# Generated by Django 5.0.3 on 2024-03-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_rename_authors_thesis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='author',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='title',
        ),
        migrations.AddField(
            model_name='thesis',
            name='firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='thesis',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
