# Generated by Django 5.0.3 on 2024-03-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_remove_thesis_abstract_remove_thesis_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='abstract',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='thesis',
            name='research_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
