# Generated by Django 5.0.3 on 2024-03-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_thesis_joined_date_thesis_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='phone',
        ),
        migrations.AddField(
            model_name='thesis',
            name='abstract',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='thesis',
            name='research_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
