# Generated by Django 5.0.3 on 2024-03-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0010_remove_thesis_joined_date_remove_thesis_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='research_title',
        ),
        migrations.AddField(
            model_name='thesis',
            name='author_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='thesis',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
