# Generated by Django 5.0.3 on 2024-03-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_remove_thesis_firstname_remove_thesis_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesis',
            old_name='author_name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='thesis',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
