# Generated by Django 5.0.3 on 2024-03-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_rename_author_name_thesis_firstname_thesis_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
